version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:1.0.0
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${LOCALHOST} #192.168.99.100 
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
   
  influxdb:
    image: influxdb:1.4
    ports:
      - "8086:8086"

  telegraf:
    build: ./telegraf
    depends_on:
     - influxdb
   
# kapacitor:
#    image: kapacitor:1.4
#    build: ./kapacitor
#    ports:
#      - "9092:9092"
  
#  chronograf:
#    image: chronograf:1.4
#    build: ./chronograf
#    ports:
#      - "8000:8000"
  
  grafana:
    build: ./grafana
    ports:
      - "3000:3000"
